name: Despliegue en Producción por Release

on:
  release:
    types: [published] # Se ejecuta solo cuando publicas la release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Railway CLI
        run: npm i -g @railway/cli

      - name: Desplegar en Railway
        run: railway up --service paqueteriaIW
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}
